### ISSUE TITLE
spring-retry is not really optional

### ISSUE THREAD

**Issue by jimirocks** [gooddata/gooddata-java#804]
trying to call `GoodData.createRestTemplate(endpoint, httpClient, null);`
getting `java.lang.NoClassDefFoundError: org/springframework/retry/RetryPolicy`

Affects both 2.X and 3.X versions

Introduced by #782

**Comment by jimirocks** [comment]
Fixed and merged also to 3.0.0-RC
